var en = function (value) {
	var labels = {
		title: 'Create a steading',

		prosperity: 'Prosperity\t',
		prosperity0: 'Dirt',
		prosperity0long: 'Nothing for sale, nobody has more than they need (and they’re lucky if they have that). Unskilled labor is cheap.',
		prosperity1: 'Poor',
		prosperity1long: 'Only the bare necessities for sale. Weapons are scarce unless the steading is heavily defended or militant. Unskilled labor is readily available.',
		prosperity2: 'Moderate',
		prosperity2long: 'Most mundane items are available. Some types of skilled laborers.',
		prosperity3: 'Wealthy',
		prosperity3long: 'Any mundane item can be found for sale. Most kinds of skilled laborers are available, but demand is high for their time.',
		prosperity4: 'Rich',
		prosperity4long: 'Mundane items and more, if you know where to find them.',

		population: 'Population\t',
		population0: 'Exodus',
		population0long: 'The steading has lost its population and is on the verge of collapse.',
		population1: 'Shrinking',
		population1long: 'The population is less than it once was. Buildings stand empty.',
		population2: 'Steady',
		population2long: 'The population is in line with the current size of the steading. Some slow growth.',
		population3: 'Growing',
		population3long: 'More people than there are buildings.',
		population4: 'Booming',
		population4long: 'Resources are stretched thin trying to keep up with the number of people.',

		defenses: 'Defenses\t\t',
		defenses0: 'None',
		defenses0long: 'Clubs, torches, farming tools.',
		defenses1: 'Militia',
		defenses1long: 'There are able-bodied men and women with worn weapons ready to be called, but no standing force.',
		defenses2: 'Watch',
		defenses2long: 'There are a few watchers posted who look out for trouble and settle small problems, but their main role is to summon the militia.',
		defenses3: 'Guard',
		defenses3long: 'There are armed defenders at all times with a total pool of less than 100 (or equivalent). There is always at least one armed patrol about the steading.',
		defenses4: 'Garrison',
		defenses4long: 'There are armed defenders at all times with a total pool of 100–300 (or equivalent). There are multiple armed patrols at all times.',
		defenses5: 'Battalion',
		defenses5long: 'As many as 1,000 armed defenders (or equivalent). The steading has manned maintained defenses as well.',
		defenses6: 'Legion',
		defenses6long: 'The steading is defended by thousands of armed soldiers (or equivalent). The steading’s defenses are intimidating.',

		steadingvillage: 'Village',
		steadingvillagebutton: 'Create a village',
		steadingvillagetext: 'Villages are the smallest steadings. They’re usually out of the way, off the main roads. If they’re lucky they can muster some defense but it’s often just rabble with pitchforks and torches. A village stands near some easily exploitable resource: rich soil, plentiful fish, an old forest, or a mine. There might be a store of some sort but more likely its people trade among themselves. Coin is scarce.',
		steadingvillagetext2: 'By default a village is Poor, Steady, Militia, Resource (your choice) and has an Oath to another steading of your choice',
		steadingtown: 'Town',
		steadingtownbutton: 'Create a town',
		steadingtowntext: 'Towns have a hundred or so inhabitants. They’re the kind of place that springs up around a mill, trading post, or inn and usually have fields, farms, and livestock of some kind. They might have a standing militia of farmers strong enough to wield a blade or shoot a bow. Towns have the basics for sale but certainly no special goods. Usually they’ll focus on a local product or two and do some trade with travelers.',
		steadingtowntext2: 'By default a town is Moderate, Steady, Watch, and Trade (two of your choice).',
		steadingkeep: 'Keep',
		steadingkeepbutton: 'Create a keep',
		steadingkeeptext: 'A keep is a steading built specifically for defense—sometimes of a particularly important location like a river delta or a rich gold mine. Keeps are found at the frontier edges of civilization. Inhabitants are inured to the day-to-day dangers of the road. They’re tough folks that number between a hundred and a thousand, depending on the size of the keep and the place it defends. Keeps won’t often have much beyond their own supplies, traded to them from nearby villages, but will almost always have arms and armor and sometimes a rare magical item found in the local wilds.',
		steadingkeeptext2: 'By default a keep is Poor, Shrinking, Guard, Need (Supplies), Trade (someplace with supplies), Oath (your choice).',
		steadingcity: 'City',
		steadingcitybutton: 'Create a city',
		steadingcitytext: 'From bustling trade center to sprawling metropolis, the city represents the largest sort of steading in Dungeon World. These are places where folk of many races and kinds can be found. They often exist at the confluence of a handful of trade routes or are built in a place of spiritual significance. They don’t often generate their own raw materials for trade, relying on supplies from villages nearby for food and resources, but will always have crafted goods and some stranger things for sale to those willing to seek them.',
		steadingcitytext2: 'By default a city is Moderate, Steady, Guard, Market, and Guild (one of your choice). It also has Oaths with at least two other steadings, usually a town and a keep.',

		optionsvillage: 'If the village is part of a kingdom or empire choose one',
		optionvillage0: 'The village is somewhere naturally defended: Safe, -Defenses',
		optionvillage1: 'The village has abundant resources that sustain it: +Prosperity, Resource (your choice), Enmity (your choice)',
		optionvillage2: 'The village is under the protection of another steading: Oath (that steading), +Defenses',
		optionvillage3: 'The village is on a major road: Trade (your choice), +Prosperity',
		optionvillage4: 'The village is built around a wizard’s tower: Personage (the wizard), Blight (arcane creatures)',
		optionvillage5: 'The village was built on the site of religious significance: Divine',
		optionvillage6: 'The village was built on the site of religious significance: History (your choice)',

		optionstown: 'If the town is listed as Trade by another steading choose one',
		optiontown0: 'The town is booming: Booming, Lawless',
		optiontown1: 'The town stands on a crossroads: Market, +Prosperity',
		optiontown2: 'The town is defended by another steading: Oath (that steading), +Defenses',
		optiontown3: 'The town is built around a church: Power (Divine)',
		optiontown4: 'The town is built around a craft: Craft (your choice), Resource (something required for that craft)',
		optiontown5: 'The town is built around a military post: +Defenses',

		optionskeep: 'If the keep is owed fealty by at least one settlement choose one',
		optionkeep0: 'The keep belongs to a noble family: +Prosperity, Power (Political)',
		optionkeep1: 'The keep is run by a skilled commander: Personage (the commander), +Defenses',
		optionkeep2: 'The keep stands watch over a trade road: +Prosperity, Guild (trade)',
		optionkeep3: 'The keep is used to train special troops: Arcane, -Population',
		optionkeep4: 'The keep is surrounded by fertile land: remove Need (Supplies)',
		optionkeep5: 'The keep stands on a border: +Defenses, Enmity (steading on the other side of the border)',

		optionscity: 'If the city has trade with at least one steading and fealty from at least one steading choose one',
		optioncity0: 'The city has permanent defenses, like walls: +Defenses, Oath (your choice)',
		optioncity1: 'The city is ruled by a single individual: Personage (the ruler), Power (Political)',
		optioncity2: 'The city is diverse: Dwarven or Elven or both',
		optioncity3: 'The city is a trade hub: Trade (every steading nearby), +Prosperity',
		optioncity4: 'The city is ancient, built on top of its own ruins: History (your choice), Divine',
		optioncity5: 'The city is a center of learning: Arcane, Craft (your choice), Power (Arcane)',

		problems: 'Choose one problem',
		problemvillage0: 'The village is in arid or uncultivable land: Need (Food)',
		problemvillage1: 'The village is dedicated to a deity: Religious (that deity), Enmity (a settlement of another deity)',
		problemvillage2: 'The village has recently fought a battle: -Population',
		problemvillage3: 'The village has recently fought a battle to the end: -Population, -Prosperity',
		problemvillage4: 'The village has recently fought a battle and lost: -Population, -Defenses',
		problemvillage5: 'The village has recently fought a battle to the end and lost: -Population, -Prosperity, -Defenses',
		problemvillage6: 'The village has a monster problem: Blight (that monster), Need (adventurers)',
		problemvillage7: 'The village has absorbed another village: +Population, Lawless',
		problemvillage8: 'The village is remote or unwelcoming: -Prosperity, Dwarven',
		problemvillage9: 'The village is remote or unwelcoming: -Prosperity, Elven',

		problemtown0: 'The town has grown too big for an important supply (like grain, wood, or stone): Need (that resource), Trade (a village or town with that resource)',
		problemtown1: 'The town offers defense to others: Oath (your choice), -Defenses',
		problemtown2: 'The town is notorious for an outlaw who is rumored to live there: Personage (the outlaw), Enmity (where the crimes were committed)',
		problemtown3: 'The town has cornered the market on a good or service: Exotic (that good or service), Enmity (a settlement with ambition)',
		problemtown4: 'The town has a disease: -Population',
		problemtown5: 'The town is a popular meeting place: +Population, Lawless',

		problemkeep0: 'The keep is built on a naturally defensible position: Safe, -Population',
		problemkeep1: 'The keep was a conquest from another power: Enmity (steadings of that power)',
		problemkeep2: 'The keep is a safe haven for brigands: Lawless',
		problemkeep3: 'The keep was built to defend from a specific threat: Blight (that threat)',
		problemkeep4: 'The keep has seen horrible bloody war: History (Battle), Blight (Restless Spirits)',
		problemkeep5: 'The keep is given the worst of the worst: Need (Skilled Recruits)',

		problemcity0: 'The city has outgrown its resources: +Population, Need (food)',
		problemcity1: 'The city has designs on nearby territory: Enmity (nearby steadings), +Defenses',
		problemcity2: 'The city is ruled by a theocracy: -Defenses, Power (Divine)',
		problemcity3: 'The city is ruled by the people: -Defenses, +Population',
		problemcity4: 'The city has supernatural defenses: +Defenses, Blight (related supernatural creatures)',
		problemcity5: 'The city lies on a place of power: Arcane, Personage (whoever watches the place of power), Blight (arcane creatures)',

		safe: 'Safe',
		safetext: 'Outside trouble doesn’t come here until the players bring it. Idyllic and often hidden, if the steading would lose or degrade another beneficial tag get rid of safe instead.',

		religion: 'Religion',
		religiondeity: 'Religion (that deity)',
		religiontext: 'The listed deity is revered here.',

		exotic: 'Exotic',
		exotictext: 'There are goods and services available here that aren’t available anywhere else nearby. List them.',

		resource: 'Resource',
		resourcecraft: 'Resource (for craft)',
		resourcetext: 'The steading has easy access to the listed resource (e.g., a spice, a type of ore, fish, grapes). That resource is significantly cheaper.',

		need: 'Need',
		needfood: 'Need (food)',
		needresource: 'need (resource)',
		needadventurers: 'need (adventurers)',
		needsupplies: 'need (supplies)',
		needrecruits: 'need (skilled recruits)',
		needtext: 'The steading has an acute or ongoing need for the listed resource. That resource sells for considerably more.',

		oath: 'Oath',
		oathtext: 'The steading has sworn oaths to the listed steadings. These oaths are generally of fealty or support, but may be more specific.',

		trade: 'Trade',
		traderesource: 'Trade (resource)',
		tradesupplies: 'Trade (supplies)',
		tradetext: 'The steading regularly trades with the listed steadings.',

		market: 'Market',
		markettext: 'Everyone comes here to trade. On any given day the available items may be far beyond their prosperity. +1 to supply.',

		enmity: 'Enmity',
		enmityotherdeity: 'Enmity (another deity\'s settlement)',
		enmitytext: 'The steading holds a grudge against the listed steadings.',

		history: 'History',
		historybattle: 'History (battle)',
		historytext: 'Something important once happened here, choose one and detail or make up your own: battle, miracle, myth, romance, tragedy.',

		arcane: 'Arcane',
		arcanetext: 'Someone in town can cast arcane spells for a price. This tends to draw more arcane casters, +1 to recruit when you put out word you’re looking for an adept.',

		divine: 'Divine',
		divinetext: 'There is a major religious presence, maybe a cathedral or monastery. They can heal and maybe even raise the dead for a donation or resolution of a quest. Take +1 to recruit priests here.',

		guild: 'Guild',
		guildtrade: 'Guild (trade)',
		guildtext: 'The listed type of guild has a major presence (and usually a fair amount of influence). If the guild is closely associated with a type of hireling, +1 to recruit that type of hireling.',

		personage: 'Personage',
		personagewizard: 'Personage (wizard)',
		personageoutlaw: 'Personage (outlaw)',
		personagecommander: 'Personage (commander)',
		personageruler: 'Personage (ruler)',
		personagetext: 'There’s a notable person who makes their home here. Give them a name and a short note on why they’re notable.',

		dwarven: 'Dwarven',
		dwarventext: 'The steading is significantly or entirely dwarves. Dwarven goods are more common and less expensive than they typically are.',

		elven: 'Elven',
		elventext: 'The steading is significantly or entirely elves. Elven goods are more common and less expensive than they typically are.',

		craft: 'Craft',
		crafttext: 'The steading is known for excellence in the listed craft. Items of their chosen craft are more readily available here or of higher quality than found elsewhere.',

		lawless: 'Lawless',
		lawlesstext: 'Crime is rampant; authority is weak.',

		blight: 'Blight',
		blightarcanecreatures: 'Blight (arcane creatures)',
		blightmonster: 'Blight (monsters)',
		blightspirits: 'Blight (restless spirits)',
		blighttext: 'The steading has a recurring problem, usually a type of monster.',

		power: 'power',
		powerdivine: 'power (divine)',
		powerpolitical: 'power (political)',
		powerarcane: 'power (arcane)',
		powertext: 'The steading holds sway of some type. Typically political, divine, or arcane.',
	}

	return labels[value] || '';
}